name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Verify build output
        run: |
          echo "Listing the files in the root directory:"
          ls -alh
          echo "Listing the files in the dist directory:"
          ls -alh dist  # Ensure that the dist directory exists and contains build files

      - name: Push build to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Deploy: Build pushed to build branch'
