name: Build and Send Vite App

on:
  push:
    branches: [main]

jobs:
  build-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js 22.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Zip Build Folder
        run: |
          cd dist
          zip -r ../dist.zip .

      - name: Send dist.zip via Webhook
        run: |
          curl -X POST https://your-hosting-site.com/deploy \
          -H "Content-Type: application/zip" \
          --data-binary @dist.zip
